name: conversion_kit_demo
description: A demo Flutter application for ConversionKit package.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  conversion_kit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
